server:
  port: 9393

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_test?userUnicode=true&charsetEncoding=utf-8&userSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
mybatis:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.dg.pojo
mapper.mappers: com.dg.mybatis.MyMapper
mapper.identity: MYSQL
